name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Despliega solo cuando hay cambios en `main`

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configuración de Node.js (opcional, para proyectos de front)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Paso 3: Instalación de dependencias y build (opcional, si tienes un front)
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Paso 4: Ejecutar pruebas
    #  - name: Run tests
     #   run: npm test

      # Paso 5: Despliegue en el servidor
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@tu-servidor << 'EOF'
          cd /ruta/a/tu/proyecto
          git pull origin main
          npm install
          npm run build
          systemctl restart servicio-aplicacion
          EOF
