// Exportación centralizada de todos los iconos
// Menu Icons
export { default as IconDashboard } from './IconDashboard.vue'
export { default as IconMap } from './IconMap.vue'
export { default as IconSearch } from './IconSearch.vue'
export { default as IconProfile } from './IconProfile.vue'
export { default as IconRoute } from './IconRoute.vue'
export { default as IconTimeline } from './IconTimeline.vue'
export { default as IconActivity } from './IconActivity.vue'
export { default as IconUpload } from './IconUpload.vue'
export { default as IconReports } from './IconReports.vue'
export { default as IconUsers } from './IconUsers.vue'
export { default as IconRoles } from './IconRoles.vue'
export { default as IconAttention } from './IconAttention.vue'

// Variantes / nuevos iconos del menú y acciones
export { default as IconActividad } from './IconActividad.vue'
export { default as IconCloseMenu } from './IconCloseMenu.vue'
export { default as IconConfigurarMeta } from './IconConfigurarMeta.vue'
export { default as IconDropdownArrow } from './IconDropdownArrow.vue'
export { default as IconDropdownArrowUp } from './IconDropdownArrowUp.vue'
export { default as CloseXIcon } from './CloseXIcon.vue'
export { default as CollapseIcon } from './CollapseIcon.vue'
export { default as DeleteIcon } from './DeleteIcon.vue'
export { default as DocumentIcon } from './DocumentIcon.vue'
export { default as DownloadIcon } from './DownloadIcon.vue'
export { default as EditIcon } from './EditIcon.vue'
export { default as LocationIcon } from './LocationIcon.vue'
export { default as PermissionsIcon } from './PermissionsIcon.vue'
export { default as RefreshIcon } from './RefreshIcon.vue'
export { default as RoleIcon } from './RoleIcon.vue'
export { default as UserIcon } from './UserIcon.vue'
export { default as ViewIcon } from './ViewIcon.vue'
export { default as TxtIcon } from './TxtIcon.vue'
export { default as AddUserIcon } from './AddUserIcon.vue'

// Logos
export { default as LogoRav } from './LogoRav.vue'
export { default as LogoGov } from './LogoGov.vue'
export { default as LogoLogout } from './LogoLogout.vue'
export { default as RavLogo } from './RavLogo.vue'
export { default as LogoRavMobile } from './LogoRavMobile.vue'
export { default as RavIcon } from './RavIcon.vue'
export { default as RavIcon2 } from './RavIcon2.vue'
export { default as ApeLaIcon } from './ApeLaIcon.vue'
export { default as FondoEmprenderIcon } from './FondoEmprenderIcon.vue'
export { default as SenaLaIcon } from './SenaLaIcon.vue'
export { default as IconoGov } from './IconoGov.vue'
export { default as IconoLogoutResponsive } from './IconoLogoutResponsive.vue'
